//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freesat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Freesat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;config&gt;
        ///	&lt;DvbsSatellite&gt;
        ///		&lt;_name&gt;Freesat&lt;/_name&gt;
        ///		&lt;_positionEast&gt;282&lt;/_positionEast&gt;
        ///	&lt;/DvbsSatellite&gt;
        ///	&lt;DvbsRegion&gt;
        ///		&lt;_isoCode&gt;GB&lt;/_isoCode&gt;
        ///	&lt;/DvbsRegion&gt;
        ///	&lt;DvbsHeadend&gt;
        ///		&lt;_csiId&gt;250282&lt;/_csiId&gt;
        ///		&lt;_languageIso639&gt;en&lt;/_languageIso639&gt;
        ///	&lt;/DvbsHeadend&gt;
        ///	&lt;Scanner&gt;
        ///		&lt;csv_name&gt;DVBViewer&lt;/csv_name&gt;
        ///		&lt;Columns&gt;
        ///			&lt;_serviceId&gt;
        ///				&lt;index&gt;18&lt;/index&gt;
        ///			&lt;/_serviceId&gt;
        ///			&lt;_positionEast&gt;
        ///				&lt;index&gt;29&lt;/index&gt;
        ///			&lt;/_positionEast&gt;
        ///			&lt;_carrierFrequency&gt;
        ///				&lt;index&gt;8&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Media Center\Settings\ProgramGuide]
        ///&quot;fAgreeTOS&quot;=dword:00000001
        ///&quot;strAgreedTOSVersion&quot;=&quot;1.0&quot;
        ///
        ///.
        /// </summary>
        internal static string EPG {
            get {
                return ResourceManager.GetString("EPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; version=&quot;1.0&quot; encoding=&quot;utf-8&quot; omit-xml-declaration=&quot;no&quot; standalone=&quot;no&quot;/&gt;
        ///	&lt;xsl:strip-space elements=&quot;*&quot;/&gt;
        ///	&lt;xsl:param name=&quot;satellite_name&quot;/&gt;
        ///	&lt;xsl:param name=&quot;satellite_positionEast&quot;/&gt;
        ///	&lt;xsl:variable name=&quot;satellite_uid&quot; select=&quot;concat(&apos;!DvbsDataSet!DvbsSatellite[&apos;,$satellite_positionEast,&apos;]&apos;)&quot;/&gt;
        ///	&lt;xsl:param name=&quot;region_isoCode&quot;/&gt;
        ///	&lt;xsl:variable name=&quot;regio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string freesat {
            get {
                return ResourceManager.GetString("freesat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\windows\ehome\loadmxf -i freesat.mxf
        ///Pause
        ///.
        /// </summary>
        internal static string loadMXF {
            get {
                return ResourceManager.GetString("loadMXF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.thegreenbutton.tv/forums/viewtopic.php?f=28&amp;t=7103
        ///
        ///Start the Media Center TV Signal setup procedure (Settings &gt; TV &gt; TV Signal &gt; Set Up TV Signal).
        ///You have to enter a region and postcode, even though they will not be used.
        ///Do not agree to the Program Guide Terms of Service. (The guide will be reenabled below.)
        ///Do not Update TV Setup Data.
        ///Cancel &apos;Examining TV Signals&apos;.
        ///Choose &apos;Let me configure my TV signal manually&apos;.
        ///Select &apos;Satellite&apos; signal type and proceed through the questions abou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Readme {
            get {
                return ResourceManager.GetString("Readme", resourceCulture);
            }
        }
    }
}
